### ISSUE TITLE
Ajust of syntax

### ISSUE THREAD

**Issue by GabrielaSchmitt** [hackergrrl/art-of-readme#69]
Hey there! 
Really nice article, but in the pt-br translation I found a syntax error that can be solved in less than 1 minute. It is just to delete the space after the brackets.  Here is an image to show where it's located. Hope it helps. 

![image](https://user-images.githubusercontent.com/86369677/142034863-2b1035a3-8870-4298-889a-41701a05f9d9.png)

**Comment by lennonjesus** [comment]
Thank you, @GabrielaSchmitt.
